### ISSUE TITLE
SHIFT is sticky when moving cursor up or left

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-keyboard-cpld#2]
When moving cursor up or left and immediately pressing for example "S" key, a <3 (heart) will appear instead. Shift is behaving as if it is released to slowly.

**Comment by deftmega** [comment]
oops, probably also core related, not CPLD - right?

**Comment by gardners** [comment]
This will be main core, not keyboard CPLD. Needs to be filed there. There is some magic for handling the simulated SHIFT key pressing there, because the CPU is so fast it was able to sometime read the cursor-right/down without time for the shift to take effect, but obviously we need to tune this up a bit.

**Comment by gardners** [comment]
Close when cross-filed.
